version: '3.8'

services:
  testmodulus:
    image: "TODO image name"
    environment:
      - USER_NAME="TODO set user name"
      - VOLUME_NAME="TODO set volume name"
    shm_size: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    volumes:
      - "data:/home/${USER_NAME}/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 131072
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.capabilities.npu == nvidia

volumes:
  data:
    name: ${VOLUME_NAME}
